@baseUrl = http://localhost:3001

### POST - Login
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "ster@gmail.com",
  "password": "Dev123"
}

### GET - Buscar Pets
GET {{baseUrl}}/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMGNmNmM0Yi0yZTRiLTQ0MjgtOTEwZC00ZWEwNGY1YTNkNGMiLCJmaXJzdF9uYW1lIjoiU3RlciIsImxhc3RfbmFtZSI6IlJvcXVlIiwiZW1haWwiOiJzdGVyQGdtYWlsLmNvbSIsImlhdCI6MTc0MzY1MTI1NywiZXhwIjoxNzQ0MjU2MDU3fQ.rpT7FH7rZHDqHCH2sd3m1H_gwCIEdfxbbXn8UvzlHRU


### POST - Cadastrar admin
POST {{baseUrl}}/admins
Content-Type: application/json

{
    "first_name": "Lucas",
    "last_name": "Silva",
    "email": "lucasgmail.com",
    "password":"Tefe@3333"
}

